name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  node-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dev dependencies
        run: yarn

      - name: Run Node tests
        run: yarn test
